### ISSUE TITLE
Cannot run webpack dev server

### ISSUE THREAD

**Issue by Nxtra** [jbesw/askjames-s3uploader#7]
I am unable to run this project locally because of trouble with the `npm run dev` instructions involving the `webpack` version of the project.

## Explanation
I am using node v10.19.0 when working with this project.
To install the dependencies I  ran `npm ci` to use all packages mentioned in the `package-lock.json`.
Next I try to run the project locally using the instructions in the `README.md`: `npm run dev`.
This fails with output:

```
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

The CLI moved into a separate package: webpack-cli
Please install 'webpack-cli' in addition to webpack itself to use the CLI
-> When using npm: npm i -D webpack-cli
-> When using yarn: yarn add -D webpack-cli
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/path-to-node-modules-of-project/node_modules/webpack-dev-server/bin/webpack-dev-server.js:84:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! s3uploader@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the s3uploader@1.0.0 dev script.
```

So I decided to follow the instructions in the error message and ran: `npm i -D webpack-cli`.
After doing this I run `npm run dev` again.
This results in the following error: 
```
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/path-to-node-modules-of-project/node_modules/webpack-dev-server/bin/webpack-dev-server.js:84:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! s3uploader@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the s3uploader@1.0.0 dev script.
````

## Configuration
* node version: v10.19.0
* npm version: 6.13.4

## Steps to reproduce
```
npm ci
npm run dev
npm i -D webpack-cli
npm run dev
```

Can you help me with instructions on how to get this project running locally?

**Comment by jbesw** [comment]
This looks like a versioning issue since the Vue frontend was created a while ago. You may find it easier to use this JSFiddle for testing the concept - https://jsfiddle.net/jbeswick/jsxbv0ny/. 

Alternatively, if you create a new Vue project using the Vue CLI and then import the Vue components, that should get you around the build issues here.

**Comment by Nxtra** [comment]
> This looks like a versioning issue since the Vue frontend was created a while ago. You may find it easier to use this JSFiddle for testing the concept - https://jsfiddle.net/jbeswick/jsxbv0ny/.
> 
> Alternatively, if you create a new Vue project using the Vue CLI and then import the Vue components, that should get you around the build issues here.

Allright that sounds good. I'll try that this weekend.
Previously I fixed it by downgrading the webpack dependencies to
```
    "webpack-bundle-analyzer": "^2.9.0",
    "webpack-dev-server": "^2.9.1",
```
